name: BradleyWilliam
favicon: null
layout_spectrum: 0.5830613758880645
typography_spectrum: 0.7015610567759722
title: Create.Inspire.Evolve
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1672064841259271
  lightness: 0.9137761336751282
  saturation: 0.365670517552644
  rhythmicContrast: 0.13042412232607603
purpose: []
