typography_spectrum: 0.45057
color:
  brandColors:
    - '#ffffff'
    - '#6dbcfe'
    - '#b6dfff'
    - '#6a8dab'
    - '#274f82'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.43068
analytics:
  google: null
  facebook: null
  twitter: null
name: BradleyWilliam
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Create.Inspire.Evolve.
description: Dynamic Sage
purpose: []
