name: BradleyWilliam
favicon: null
layout_spectrum: 0.31191
typography_spectrum: 0.45057
title: Create.Inspire.Evolve
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f8fc'
    - '#27e4ec'
    - '#043562'
    - '#1798b5'
    - '#88901b'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.13042412232607603
purpose: []
