name: BradleyWilliam
favicon: null
layout_spectrum: 0.14833
typography_spectrum: 0.45057
title: Create.Inspire.Evolve
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#013777'
    - '#387ad1'
    - '#7199d7'
    - '#c2e8f5'
    - '#4e5484'
  brandStrength: 0.9375
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
